extends:
  - "spectral:oas"

rules:
  runtime-requires-401:
    description: "Runtime endpoints must document 401 (auth gate)."
    message: "Add a 401 response for this runtime operation."
    severity: error
    given: "$.paths[?(@property.match(/^(\\/api\\/(instances|workflows)\\b.*)/))][*].responses"
    then:
      - function: schema
        functionOptions:
          schema: {type: object, required: ["401"]}

  runtime-requires-429:
    description: "Runtime endpoints must document 429 (rate limiting)."
    message: "Add a 429 response for this runtime operation."
    severity: error
    given: "$.paths[?(@property.match(/^(\\/api\\/(instances|workflows)\\b.*)/))][*].responses"
    then:
      - function: schema
        functionOptions:
          schema: {type: object, required: ["429"]}

  runtime-requires-security:
    description: "Runtime endpoints must declare operation-level security."
    message: "Add an operation-level 'security' array for gated runtime routes."
    severity: error
    given: "$.paths[?(@property.match(/^(\\/api\\/(instances|workflows)\\b.*)/))][*]"
    then:
      - field: security
        function: truthy

  operation-operationId:
    description: "Each operation must have a unique operationId."
    message: "Missing operationId."
    severity: error
    given: "$.paths[*][*]"
    then:
      - field: operationId
        function: truthy
